services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - IP=0.0.0.0
      - PORT=${PORT:-8000}